language: go

go:
  - 1.11.x
  - 1.10.x
  - 1.9.x
  - master

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.15.0
        - make dep
        - make lint
    - stage: test
      script:
        - make test

matrix:
  allow_failures:
    - go: master
  fast_finish: true
